### ISSUE TITLE
Remove the length validation

### ISSUE THREAD

**Issue by akshayvadher** [akshayvadher/cuid2#12]
Revert #10 

Because I tested the original library and the following works,
```javascript
const id = init({ length: 150 });
console.log(id());
// p0m6ycspza37iwloxpn5zw0nqtbkbcycha5mm6jlqzsu33qrlh84kmkvi41qt2w5khcddvb7a50wsczoy1o795rs75b3ifld3u
```

So 
1. this does not match with the original spec. 
2. since we are returning error, user cannot use this inline, they will have to define it first and then pass
```go
myFunction(CreateId()) // this won't work

id, err := CreateId()
myFunction(id) // only this will work. This is cumbersome and for most cases, not required.
```

**Comment by akshayvadher** [comment]
Added panic instead of error because the gain from validation was too small as compared to usability issue

**Comment by sergeevabc** [comment]
I'm confused. What kind of validation is that?

``` console
$ cuid validate aa
Valid CUID2 "aa"
```

**Comment by akshayvadher** [comment]
@sergeevabc, can you elaborate more? is your issue related to "remove length validation" (this thread) issue? Also, you are using `cuid` not `cuid2`, so did you mean to check this or something else? 

In anycase, this library is just port of the original library, for original library, this is a correct CUID2, refer this https://github.com/paralleldrive/cuid2/blob/main/src/index.js#L110

**Comment by sergeevabc** [comment]
Re: @akshayvadher 

I assumed that `cuid2` relies on stricter rules when generating and, consequently, verifying IDs, which is why I was confused that just "aa" could be a valid ID.
